In [2]:
import pandas as pd
import random
from random import randrange
import datetime

In [12]:
Measurements = pd.DataFrame(columns = ['cnfgr_msrmt_id', 'elmt_seq_num', 'beg_cptr_ts', 'end_cptr_ts', 
                                    'msrmt_duration_in_min', 'val', 'val_cnt', 'msrmt_typ_dsc', 'agrgtn_typ_dsc',
                                    'msrmt_dsc', 'dim_dsc', 'uom', 'elmt_dsc', 'msrmt_nm'])

In [13]:
for i in range(10000):
    
    #cnfgr_msrmt_id
    cnfgr_msrmt_id = randrange(1000)
    
    #elmt_seq_num
    elmt_seq_num = randrange(3)
    
    #beg_cptr_ts
    
    year = randrange(2019,2021)
    month = randrange(1, 12)
    day = randrange(1, 25)
    beg_cptr_ts = datetime.datetime(year, month, day, randrange(0, 12), randrange(0, 59), randrange(0,59), randrange(1000000))

    #end_cptr_ts
    end_cptr_ts = datetime.datetime(year, month, day, randrange(0, 12), randrange(0, 59), randrange(0,59), randrange(1000000))

    #msrmt_duration_in_min
    msrmt_duration_in_min = (end_cptr_ts - beg_cptr_ts).seconds/60
    
    #val
    val = msrmt_duration_in_min/60
    
    #val_cnt
    val_cnt = randrange(20)
    
    #msrmt_typ_dsc
    msrmt_typ_dscs = ['timer', 'min val', 'max val', 'last', 'integral']
    msrmt_typ_dsc = random.choice(msrmt_typ_dscs)
    
    #agrgtn_typ_dsc
    agrgtn_typ_dsc = randrange(10)
    
    #msrmt_dsc
    msrmt_dsc = randrange(10)
    
    #dim_dsc
    dim_dscs = ['bucket1', 'bucket2', 'bucket3', 'bucket4', 'bucket5']
    dim_dsc = random.choice(msrmt_typ_dscs)
    
    #uom
    uoms = ['seconds', 'KPH']
    uom = random.choice(uoms)
    
    #elmt_dsc
    elmt_dsc = randrange(10)
    
    #msrmt_nm
    msrmt_nms = ['bucket1', 'bucket2', 'bucket3', 'bucket4', 'bucket5']
    msrmt_nm = random.choice(msrmt_nms)

    new_row = {'cnfgr_msrmt_id' : cnfgr_msrmt_id, 
           'elmt_seq_num' : elmt_seq_num, 
           'beg_cptr_ts' : beg_cptr_ts, 
           'end_cptr_ts' : end_cptr_ts, 
           'msrmt_duration_in_min' : msrmt_duration_in_min, 
           'val' : val, 
           'val_cnt' : val_cnt, 
           'msrmt_typ_dsc' : msrmt_typ_dsc, 
           'agrgtn_typ_dsc' : agrgtn_typ_dsc, 
           'msrmt_dsc' : msrmt_dsc, 
           'dim_dsc' : dim_dsc, 
           'uom' : uom, 
           'elmt_dsc' : elmt_dsc, 
           'msrmt_nm' : msrmt_nm}

    Measurements = Measurements.append(new_row, ignore_index = True)

In [14]:
Measurements

,cnfgr_msrmt_id,elmt_seq_num,beg_cptr_ts,end_cptr_ts,msrmt_duration_in_min,val,val_cnt,msrmt_typ_dsc,agrgtn_typ_dsc,msrmt_dsc,dim_dsc,uom,elmt_dsc,msrmt_nm
0,506,2,2019-05-16 04:20:55.793838,2019-05-16 09:10:47.111667,289.850000,4.830833,5,last,8,8,max val,seconds,9,bucket5
1,651,1,2019-11-04 04:27:44.327037,2019-11-04 06:39:40.662395,131.933333,2.198889,18,min val,1,0,max val,KPH,0,bucket2
2,483,2,2020-04-09 11:05:41.049571,2020-04-09 04:00:15.174454,1014.566667,16.909444,16,timer,6,3,max val,KPH,2,bucket3
3,220,2,2019-05-18 09:41:14.485965,2019-05-18 10:45:31.188822,64.266667,1.071111,8,max val,7,0,min val,seconds,6,bucket5
4,761,0,2019-01-18 10:33:49.752056,2019-01-18 11:46:53.430967,73.050000,1.217500,14,timer,0,7,max val,seconds,6,bucket4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,2019-06-20 08:37:57.707824,2019-06-20 05:08:21.270672,1230.383333,20.506389,7,max val,5,2,min val,KPH,1,bucket3
9996,122,0,2020-01-07 00:33:52.386710,2020-01-07 09:48:28.739950,554.600000,9.243333,11,timer,5,2,last,KPH,5,bucket2
9997,331,2,2019-03-19 02:13:31.179428,2019-03-19 06:13:37.903625,240.100000,4.001667,1,timer,7,1,integral,seconds,7,bucket3
9998,16,1,2020-03-19 09:17:48.273055,2020-03-19 06:17:35.508036,1259.783333,20.996389,9,timer,0,8,max val,KPH,4,bucket4
9999,23,1,2020-11-02 02:10:06.340617,2020-11-02 11:54:12.727125,584.100000,9.735000,3,max val,8,9,integral,seconds,2,bucket4

In [16]:
Measurements.to_csv('Measurements.csv')