In [26]:
import pandas as pd
import random
from random import randrange
import datetime

In [31]:
Key_Cycles = pd.DataFrame(columns = ['key_cycle_id', 'key_cycle_start', 'key_cycle_end', 'key_on_hrs', 'key_cycle_engine_hrs', 'hours_since_prev_key_cycle'])

In [32]:
for i in range(1000):
    
    #key_cycle_id
    key_cycle_id = randrange(1000000, 100000000)
    
    #key_cycle_start
    year = randrange(2019,2021)
    month = randrange(1, 12)
    day = randrange(1, 25)
    key_cycle_start = datetime.datetime(year, month, day, randrange(0, 12), randrange(0, 59), randrange(0,59), randrange(1000000))

    #key_cycle_end
    key_cycle_end = datetime.datetime(year, month, day, randrange(0, 12), randrange(0, 59), randrange(0,59), randrange(1000000))
    
    #key_on_hrs
    key_on_hrs = (key_cycle_end - key_cycle_start).seconds/3600
    

    #key_cycle_engine_hrs
    key_cycle_engine_hrs = random.uniform(0, 24)
    
    #hours_since_prev_key_cycle
    hours_since_prev_key_cycle = random.uniform(0, 24)


    new_row = {'key_cycle_id' : key_cycle_id, 
           'key_cycle_start' : key_cycle_start, 
           'key_cycle_end' : key_cycle_end, 
           'key_on_hrs' : key_on_hrs, 
           'key_cycle_engine_hrs' : key_cycle_engine_hrs, 
           'hours_since_prev_key_cycle' : hours_since_prev_key_cycle}

    Key_Cycles = Key_Cycles.append(new_row, ignore_index = True)

In [33]:
Key_Cycles

,key_cycle_id,key_cycle_start,key_cycle_end,key_on_hrs,key_cycle_engine_hrs,hours_since_prev_key_cycle
0,67666966,2020-11-12 01:22:16.882216,2020-11-12 06:22:49.110827,5.008889,11.258048,20.135381
1,16984407,2020-07-09 02:58:00.173392,2020-07-09 01:52:03.677442,22.900833,0.443717,18.603731
2,19181009,2020-11-22 01:28:40.065044,2020-11-22 06:48:29.875899,5.330278,20.329413,17.855238
3,73534099,2019-01-14 02:03:30.650406,2019-01-14 05:01:00.843316,2.958333,21.176888,8.815962
4,10875996,2020-01-05 08:21:25.488266,2020-01-05 06:18:12.144127,21.946111,7.887161,20.607099
...,...,...,...,...,...,...
995,9806321,2019-03-09 05:02:21.154981,2019-03-09 09:23:35.251986,4.353889,5.141747,8.079101
996,62252577,2020-04-02 00:50:57.976046,2020-04-02 01:50:40.029480,0.995000,5.987629,11.600352
997,63972922,2020-11-11 05:26:41.515942,2020-11-11 08:28:17.857464,3.026667,13.359460,20.639818
998,20400317,2019-07-19 01:20:10.943943,2019-07-19 06:19:15.706704,4.984444,10.819843,1.195405
999,17774304,2019-10-16 09:31:34.964190,2019-10-16 04:09:00.438193,18.623611,18.686344,0.536464

In [34]:
Key_Cycles.to_csv('Key_Cycles.csv')